# Generated by Django 5.1.1 on 2024-10-22 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('student_class', models.CharField(blank=True, max_length=10)),
                ('roll_number', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_class', models.CharField(blank=True, max_length=10)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('center', models.CharField(blank=True, max_length=100)),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.student')),
            ],
        ),
    ]
